translations = {
    "en": {
        "start": "Hello! I am a bot for submitting actor questionnaires. Shall we start?",
        "questions": [
            "First name",
            "Last name",
            "Date of birth",
            "Phone",
            "Email",
            "Social media link",
            "Sizes",
            "Hair colour",
            "Eyes colour",
            "Type",
            "Actors skills",
            "Language",
            "Driver license",
        ],
        "send_photos": "Please send 1-3 photos of yourself.",
        "thank_you": "Thank you for completing the questionnaire!",
    },
    "ua": {
        "start": "Привіт! Я бот для подачі анкет акторів. Почнемо?",
        "questions": [
            "Ім'я",
            "Прізвище",
            "Дата народження",
            "Телефон",
            "Електронна пошта",
            "Посилання на соціальні мережі",
            "Розміри",
            "Колір волосся",
            "Колір очей",
            "Тип",
            "Акторська майстерність",
            "Мова",
            "Водійські права",
        ],
        "send_photos": "Будь ласка, надішліть 1-3 свої фотографії.",
        "thank_you": "Дякуємо за заповнення анкети!",
    },
}
